baseURL = "https://csw609.github.io"
languageCode = 'en-us'
title = "최석원의 지식 보고"

theme = "m10c"
paginate = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "https://github.com/csw609/csw609"
    weight = 2

[params]
  author = "최석원"
  description = "지식을 나눕시다!"
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/csw609"


